-- TRUNCATE "Course" CASCADE ;
-- TRUNCATE "Student" CASCADE ;


insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'GENERAL AGRICULTURE');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'AGRICULTURE PRODUCTION AND MANAGEMENT');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'AGRICULTURAL ECONOMICS');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'ANIMAL SCIENCES');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'FOOD SCIENCE');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'PLANT SCIENCE AND AGRONOMY');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'SOIL SCIENCE');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'MISCELLANEOUS AGRICULTURE');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'FORESTRY');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'NATURAL RESOURCES MANAGEMENT');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'FINE ARTS');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'DRAMA AND THEATER ARTS');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'MUSIC');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'VISUAL AND PERFORMING ARTS');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'COMMERCIAL ART AND GRAPHIC DESIGN');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'FILM VIDEO AND PHOTOGRAPHIC ARTS');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'STUDIO ARTS');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'MISCELLANEOUS FINE ARTS');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'ENVIRONMENTAL SCIENCE');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'BIOLOGY');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'BIOCHEMICAL SCIENCES');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'BOTANY');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'MOLECULAR BIOLOGY');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'ECOLOGY');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'GENETICS');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'MICROBIOLOGY');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'PHARMACOLOGY');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'PHYSIOLOGY');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'ZOOLOGY');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'NEUROSCIENCE');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'MISCELLANEOUS BIOLOGY');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'COGNITIVE SCIENCE AND BIOPSYCHOLOGY');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'GENERAL BUSINESS');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'ACCOUNTING');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'ACTUARIAL SCIENCE');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'BUSINESS MANAGEMENT AND ADMINISTRATION');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'OPERATIONS LOGISTICS AND E-COMMERCE');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'BUSINESS ECONOMICS');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'MARKETING AND MARKETING RESEARCH');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'FINANCE');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'HUMAN RESOURCES AND PERSONNEL MANAGEMENT');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'INTERNATIONAL BUSINESS');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'HOSPITALITY MANAGEMENT');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'MANAGEMENT INFORMATION SYSTEMS AND STATISTICS');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'MISCELLANEOUS BUSINESS & MEDICAL ADMINISTRATION');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'COMMUNICATIONS');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'JOURNALISM');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'MASS MEDIA');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'ADVERTISING AND PUBLIC RELATIONS');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'COMMUNICATION TECHNOLOGIES');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'COMPUTER AND INFORMATION SYSTEMS');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'COMPUTER PROGRAMMING AND DATA PROCESSING');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'COMPUTER SCIENCE');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'INFORMATION SCIENCES');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'COMPUTER ADMINISTRATION MANAGEMENT AND SECURITY');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'COMPUTER NETWORKING AND TELECOMMUNICATIONS');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'MATHEMATICS');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'APPLIED MATHEMATICS');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'STATISTICS AND DECISION SCIENCE');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'MATHEMATICS AND COMPUTER SCIENCE');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'GENERAL EDUCATION');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'EDUCATIONAL ADMINISTRATION AND SUPERVISION');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'SCHOOL STUDENT COUNSELING');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'ELEMENTARY EDUCATION');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'MATHEMATICS TEACHER EDUCATION');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'PHYSICAL AND HEALTH EDUCATION TEACHING');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'EARLY CHILDHOOD EDUCATION');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'SCIENCE AND COMPUTER TEACHER EDUCATION');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'SECONDARY TEACHER EDUCATION');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'SPECIAL NEEDS EDUCATION');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'SOCIAL SCIENCE OR HISTORY TEACHER EDUCATION');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'TEACHER EDUCATION: MULTIPLE LEVELS');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'LANGUAGE AND DRAMA EDUCATION');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'ART AND MUSIC EDUCATION');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'MISCELLANEOUS EDUCATION');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'LIBRARY SCIENCE');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'ARCHITECTURE');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'GENERAL ENGINEERING');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'AEROSPACE ENGINEERING');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'BIOLOGICAL ENGINEERING');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'ARCHITECTURAL ENGINEERING');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'BIOMEDICAL ENGINEERING');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'CHEMICAL ENGINEERING');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'CIVIL ENGINEERING');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'COMPUTER ENGINEERING');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'ELECTRICAL ENGINEERING');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'ENGINEERING MECHANICS PHYSICS AND SCIENCE');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'ENVIRONMENTAL ENGINEERING');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'GEOLOGICAL AND GEOPHYSICAL ENGINEERING');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'INDUSTRIAL AND MANUFACTURING ENGINEERING');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'MATERIALS ENGINEERING AND MATERIALS SCIENCE');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'MECHANICAL ENGINEERING');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'METALLURGICAL ENGINEERING');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'MINING AND MINERAL ENGINEERING');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'NAVAL ARCHITECTURE AND MARINE ENGINEERING');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'NUCLEAR ENGINEERING');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'PETROLEUM ENGINEERING');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'MISCELLANEOUS ENGINEERING');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'ENGINEERING TECHNOLOGIES');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'ENGINEERING AND INDUSTRIAL MANAGEMENT');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'ELECTRICAL ENGINEERING TECHNOLOGY');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'INDUSTRIAL PRODUCTION TECHNOLOGIES');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'MECHANICAL ENGINEERING RELATED TECHNOLOGIES');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'MISCELLANEOUS ENGINEERING TECHNOLOGIES');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'MATERIALS SCIENCE');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'NUTRITION SCIENCES');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'GENERAL MEDICAL AND HEALTH SERVICES');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'COMMUNICATION DISORDERS SCIENCES AND SERVICES');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'HEALTH AND MEDICAL ADMINISTRATIVE SERVICES');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'MEDICAL ASSISTING SERVICES');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'MEDICAL TECHNOLOGIES TECHNICIANS');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'HEALTH AND MEDICAL PREPARATORY PROGRAMS');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'NURSING');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'PHARMACY PHARMACEUTICAL SCIENCES AND ADMINISTRATION');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'TREATMENT THERAPY PROFESSIONS');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'COMMUNITY AND PUBLIC HEALTH');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'MISCELLANEOUS HEALTH MEDICAL PROFESSIONS');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'AREA ETHNIC AND CIVILIZATION STUDIES');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'LINGUISTICS AND COMPARATIVE LANGUAGE AND LITERATURE');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'FRENCH GERMAN LATIN AND OTHER COMMON FOREIGN LANGUAGE STUDIES');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'OTHER FOREIGN LANGUAGES');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'ENGLISH LANGUAGE AND LITERATURE');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'COMPOSITION AND RHETORIC');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'LIBERAL ARTS');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'HUMANITIES');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'INTERCULTURAL AND INTERNATIONAL STUDIES');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'PHILOSOPHY AND RELIGIOUS STUDIES');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'THEOLOGY AND RELIGIOUS VOCATIONS');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'ANTHROPOLOGY AND ARCHEOLOGY');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'ART HISTORY AND CRITICISM');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'HISTORY');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'UNITED STATES HISTORY');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'COSMETOLOGY SERVICES AND CULINARY ARTS');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'FAMILY AND CONSUMER SCIENCES');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'MILITARY TECHNOLOGIES');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'PHYSICAL FITNESS PARKS RECREATION AND LEISURE');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'CONSTRUCTION SERVICES');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, '');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'ELECTRICAL, MECHANICAL, AND PRECISION TECHNOLOGIES AND PRODUCTION');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'TRANSPORTATION SCIENCES AND TECHNOLOGIES');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'MULTI/INTERDISCIPLINARY STUDIES');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'COURT REPORTING');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'PRE-LAW AND LEGAL STUDIES');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'CRIMINAL JUSTICE AND FIRE PROTECTION');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'PUBLIC ADMINISTRATION');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'PUBLIC POLICY');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'PHYSICAL SCIENCES');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'ASTRONOMY AND ASTROPHYSICS');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'ATMOSPHERIC SCIENCES AND METEOROLOGY');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'CHEMISTRY');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'GEOLOGY AND EARTH SCIENCE');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'GEOSCIENCES');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'OCEANOGRAPHY');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'PHYSICS');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'MULTI-DISCIPLINARY OR GENERAL SCIENCE');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'NUCLEAR');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'INDUSTRIAL RADIOLOGY');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'AND BIOLOGICAL TECHNOLOGIES');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'PSYCHOLOGY');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'EDUCATIONAL PSYCHOLOGY');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'CLINICAL PSYCHOLOGY');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'COUNSELING PSYCHOLOGY');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'INDUSTRIAL AND ORGANIZATIONAL PSYCHOLOGY');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'SOCIAL PSYCHOLOGY');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'MISCELLANEOUS PSYCHOLOGY');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'HUMAN SERVICES AND COMMUNITY ORGANIZATION');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'SOCIAL WORK');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'INTERDISCIPLINARY SOCIAL SCIENCES');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'GENERAL SOCIAL SCIENCES');
insert into "Course" ("CourseID", "CourseName") values (DEFAULT, 'ECONOMICS');


insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Polly Neely', '837 Surrey Court', 6);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Zia Fadden', '031 Nobel Plaza', 113);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Stacia Grigorey', '5 Merchant Place', 86);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Mark Coot', '640 Hovde Plaza', 34);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Xenia Woolsey', '6 Oakridge Lane', 94);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Milli Hazelgreave', '29280 Anhalt Center', 28);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Anton Binton', '4643 Division Parkway', 123);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Blancha Hitter', '8018 Corben Court', 8);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Kathryne Deschelle', '32499 Algoma Lane', 28);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Esme Ball', '2004 Donald Lane', 99);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Lonny Gosden', '9155 Bluestem Hill', 11);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Linnell Oddboy', '54322 Monterey Plaza', 3);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Delmore Elson', '55754 Eagan Avenue', 35);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Thayne Inseal', '3421 Emmet Way', 126);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Dorothy Bowart', '0497 Sunfield Trail', 133);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Skipp Siret', '76 Monument Park', 7);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Roxi Wiburn', '79 Badeau Way', 156);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Mella O'' Finan', '07 Stephen Junction', 142);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Gerrie Killiam', '93056 Sachtjen Crossing', 93);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Pyotr Gibbieson', '320 East Alley', 39);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Hollyanne Bardell', '09378 Westerfield Place', 164);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Randi Cossey', '9416 Thackeray Junction', 58);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Gal Yarker', '88 Bultman Hill', 154);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Meridith Boughey', '4 High Crossing Road', 133);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Denny Doulden', '0 Park Meadow Road', 151);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Petronia Ghilardi', '49 Cody Plaza', 69);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Antonie Beevens', '8217 David Street', 43);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Hulda MacDirmid', '811 Arrowood Plaza', 43);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Daniel Cappel', '545 Transport Alley', 25);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Baillie Landa', '3049 Kings Center', 115);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Rahel Stratton', '875 Brown Drive', 109);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Ailee Melby', '329 Superior Alley', 28);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Maximilian Ickowicz', '715 Corben Alley', 88);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Brendis Athow', '75316 Norway Maple Point', 10);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Halimeda Sieghart', '2 Mcbride Court', 57);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Winny Boteman', '43857 Sheridan Place', 123);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Marjie Orton', '7 Maywood Avenue', 117);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Cathee Matthewson', '6 Marquette Trail', 23);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Inesita Baxster', '29606 Luster Court', 19);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Vivyanne Pershouse', '3 5th Plaza', 51);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Mikol Harlett', '36 Myrtle Crossing', 76);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Deeann Vardon', '5187 Delaware Center', 134);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Mandel Fielding', '21171 Hauk Junction', 161);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Heloise Tewkesberry', '557 Dorton Avenue', 153);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Leslie Legonidec', '98796 Prairieview Pass', 22);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Star Powland', '64 Rockefeller Junction', 74);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Gael Stoakley', '57604 Judy Center', 147);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Valida Golt', '2 Browning Hill', 167);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Anneliese Martyntsev', '1677 Burrows Center', 127);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Maggee Oakenfull', '97 Mosinee Junction', 12);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Ethyl Ducker', '942 Logan Place', 59);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Rheba Gallemore', '22485 Reindahl Street', 83);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Alix Cram', '6551 Briar Crest Park', 90);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Zarah Dinsey', '63133 Warner Court', 27);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Phoebe Gelland', '7 Everett Junction', 37);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Carney Snassell', '994 Weeping Birch Junction', 163);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Gaylor Maxted', '691 West Center', 51);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Lory Follows', '2 Susan Trail', 121);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Bondie Eastup', '8202 Express Way', 150);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Paxon Harte', '514 Westport Court', 163);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Katrinka Forlonge', '53294 Sutherland Hill', 102);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Salvatore Ouldred', '923 Mitchell Center', 7);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Darlleen Maple', '77104 Hoard Hill', 170);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Chrotoem Sotheby', '4 Fulton Way', 74);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Kassia Forsythe', '9653 Mayfield Junction', 22);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Kira Pendlebury', '83175 Delaware Avenue', 52);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Shaine Rosenwald', '2430 Johnson Hill', 81);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Jania Kempstone', '18 Holmberg Way', 119);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Ina Whitehorn', '2221 Sheridan Lane', 119);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Fredra Hinksen', '9 Wayridge Center', 103);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Amargo Rodden', '67 Chive Crossing', 14);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Essie Southernwood', '850 Sommers Way', 119);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Barbabra Vango', '0 Oak Valley Alley', 21);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Kary Spittle', '6 Glendale Circle', 3);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Alasteir Lubbock', '182 Arrowood Avenue', 123);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Johnath Spoors', '0 Ludington Place', 64);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Tye Gedney', '311 Bultman Circle', 26);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Weidar Dixson', '58959 Fordem Terrace', 134);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Cori Bennitt', '9476 Shopko Alley', 131);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Odelia Coveley', '3 Cottonwood Road', 136);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Ignazio Alpine', '61 Burrows Parkway', 3);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Keen Setter', '7 8th Plaza', 35);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Gaby Mallabar', '32106 Karstens Place', 101);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Bethany Trodd', '4 Marcy Way', 39);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Bram Lemmers', '897 Mitchell Terrace', 138);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Nealson McLane', '3187 Toban Center', 159);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Gonzales Richardin', '75 Buell Avenue', 20);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Winfred Ellwood', '56291 Menomonie Pass', 116);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Edmund Bruniges', '88016 Sunnyside Circle', 127);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Sherlocke Grichukhin', '50 Mitchell Place', 32);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Fritz Vennart', '68 Eastlawn Way', 43);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Andris Laskey', '00793 Longview Plaza', 98);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Ardra Daymont', '3 Chive Plaza', 147);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Stephen Gershom', '97 Coolidge Park', 167);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Lorry Barrowcliff', '2 Tony Avenue', 98);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Dela Blaiklock', '545 Vera Circle', 51);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Huntley Boyland', '33360 Corry Lane', 141);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Laurianne Fardell', '707 Vera Way', 20);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Douglass Gregoletti', '17 Maryland Terrace', 55);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Dunstan Cruickshank', '01 Mosinee Pass', 13);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Paloma Gerriessen', '1692 Clarendon Lane', 87);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Barbabra Byer', '0 Debs Drive', 42);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Fae Matuszak', '392 Beilfuss Avenue', 141);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Sonnie Cawthera', '3 Dahle Crossing', 59);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Kennith Fossey', '40 Marcy Way', 83);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Hy Sommersett', '87989 Grim Park', 97);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Elyse Foch', '972 Carpenter Circle', 141);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Paolo Madden', '61 Mitchell Avenue', 127);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Rouvin Eakley', '19 Village Lane', 4);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Bridgette Cassius', '4955 Katie Pass', 34);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Murial Poor', '00 Coolidge Place', 77);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Orelle Ixor', '4161 Garrison Circle', 19);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Angie Chesnut', '973 Sage Plaza', 68);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Berky Husby', '599 Clyde Gallagher Alley', 70);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Rodolphe Gidney', '2 Muir Point', 104);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Harland Thieme', '0874 Westport Plaza', 25);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Germain Free', '3 Loftsgordon Way', 112);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Audra Helstrip', '1209 Hollow Ridge Park', 15);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Burtie Marzelli', '32 Parkside Point', 123);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Bone Gornal', '979 Golf Course Road', 102);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Nerti Seavers', '0906 Blackbird Street', 125);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Izaak Iacovini', '70387 Karstens Plaza', 156);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Odie Rainsdon', '6 Hansons Alley', 73);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Tris Haton', '996 Eastwood Center', 165);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Wilie Whatling', '0 Service Street', 150);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Rebeka Robers', '79 Goodland Plaza', 165);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Clayton Eager', '42624 Kenwood Junction', 145);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Bonnie Diable', '00 Reinke Hill', 132);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Willy Fragino', '51437 Sheridan Point', 88);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Ethan Aronovitz', '9817 John Wall Avenue', 5);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Malynda Rosborough', '61145 Gateway Court', 31);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Christabella MacGaughey', '52 Fremont Alley', 141);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Rollin Starr', '366 La Follette Hill', 58);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Urbain Kristof', '34 Sommers Street', 71);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Ladonna Buchanan', '07 Mendota Trail', 47);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Jemmie Ringrose', '1 Delaware Court', 92);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Jorie Ridder', '660 Longview Pass', 105);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Manda McOnie', '668 Homewood Trail', 101);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Ave Weddeburn', '392 Kenwood Drive', 21);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Bunni Du Barry', '6 Sullivan Parkway', 87);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Gray Dennert', '8655 Novick Parkway', 49);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Carmencita McCoid', '480 Sunbrook Crossing', 82);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Pru Rudolf', '4 Tony Lane', 101);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Zachary Ivashnyov', '6 Grasskamp Place', 75);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Joete Matchett', '8 Londonderry Circle', 45);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Shanda Leet', '56 Orin Point', 37);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Leanna Gribble', '8392 Fairview Parkway', 84);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Nathan Drinkhall', '442 Derek Way', 76);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Janie Mityashev', '341 Hallows Plaza', 114);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Jacky Bulpitt', '90147 Jenna Circle', 81);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Birdie Gatteridge', '1 Walton Hill', 71);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Amory Shire', '380 Sunbrook Place', 19);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Pat Scourgie', '507 Ridge Oak Junction', 22);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Marcello Paradyce', '7657 Nancy Place', 129);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Cassandry Benn', '153 Golf View Lane', 94);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Valera Campos', '95211 Gina Road', 133);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Vernice Lightbourne', '653 Fairview Drive', 115);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Fernandina Benduhn', '0 Dennis Road', 34);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Othilia Thresher', '91 Ramsey Hill', 49);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Elaina Menere', '96 Autumn Leaf Road', 136);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Bessy Frodsham', '71006 Wayridge Hill', 80);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Balduin Glastonbury', '68 Tennyson Pass', 55);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Nollie Redwing', '4 Schlimgen Park', 166);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Linette Chrippes', '42558 Bunker Hill Point', 68);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Sid Stroder', '3 Rowland Center', 115);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Finley Pietrowski', '654 Lien Circle', 21);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Rennie Happer', '90751 Farragut Junction', 54);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Toby Milne', '1166 Aberg Alley', 6);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Ellie Scannell', '53428 Mayfield Circle', 11);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Druci Huntly', '398 Weeping Birch Terrace', 43);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Shoshana Applin', '505 Schlimgen Alley', 132);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Annecorinne Dickons', '47934 Fairview Circle', 62);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Warner Wimms', '6 Ilene Point', 109);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Daile Scrase', '14 Dwight Crossing', 79);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Sharona Hoodless', '1084 Homewood Junction', 90);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Lelia Drohun', '4 Sullivan Circle', 109);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Eddy Bigglestone', '9592 Grim Avenue', 30);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Thea Benns', '2684 Briar Crest Pass', 101);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Helen-elizabeth Benka', '98 Cherokee Drive', 132);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Lloyd Kimmitt', '1 Hauk Park', 127);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Chantalle Arrandale', '1139 Hazelcrest Crossing', 168);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Wendell Luscombe', '29 Elmside Pass', 135);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Mateo Stoeckle', '02 Golden Leaf Road', 142);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Ketty Blackwell', '04 8th Lane', 16);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Antonia Vela', '7716 Scott Crossing', 71);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Dodie Gardener', '6236 Duke Street', 4);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Tarrance Lesly', '99472 Bowman Junction', 74);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Dukie Crookston', '5766 Rutledge Street', 129);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Merridie Nanni', '5 Anthes Drive', 157);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Cassaundra Assandri', '03998 Di Loreto Avenue', 120);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Merola Jeal', '74 Texas Pass', 143);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Jeane Tagg', '38 Cody Place', 4);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Frederich Advani', '33 Ohio Parkway', 81);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Elisabetta Dayne', '68 Ronald Regan Point', 80);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Zorana Zanolli', '84043 Beilfuss Trail', 3);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Sabrina Biskup', '307 Thompson Junction', 119);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Shannon Pummery', '098 Maple Wood Street', 121);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Georgena Ellsbury', '4 Merry Terrace', 24);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Eveleen Prayer', '8 Walton Alley', 42);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Oliver Rawnsley', '03421 Northridge Center', 44);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Kerby Sperring', '1491 Farwell Terrace', 93);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Catherine Liddell', '5 Lighthouse Bay Avenue', 20);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Sonya Relph', '99 Rusk Junction', 71);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Amelie Glyde', '49065 Cambridge Park', 163);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Janka Gress', '2 Fair Oaks Drive', 14);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Lorne Wickins', '31 Spaight Hill', 5);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Shani Dowrey', '37697 Debra Plaza', 39);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Carroll Tzarkov', '0 American Lane', 98);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Sabine Jarman', '6873 Truax Terrace', 29);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Vergil Yeowell', '56 Kipling Plaza', 50);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Arny Shoesmith', '26279 Lillian Lane', 64);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Aubert Cunniffe', '40 Troy Center', 46);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Roscoe Helliwell', '351 Westport Parkway', 143);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Angelica Guesford', '73409 Oak Hill', 76);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Gabie Trillow', '49 Monument Circle', 138);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Kris Putten', '983 Summer Ridge Pass', 30);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Sheilah Bilney', '542 Arizona Street', 162);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Jakie Novis', '32483 Lerdahl Alley', 37);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Dion Aspden', '49 Eagle Crest Place', 79);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Sharlene Bras', '8 Sycamore Way', 165);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Anthony Scammonden', '21811 Bashford Place', 135);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Bearnard Argente', '9949 Old Gate Alley', 21);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Mollee Oxenden', '3469 Warner Road', 38);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Brittney Jannex', '47 Parkside Place', 137);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Kiel Hammell', '56420 Crownhardt Terrace', 12);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Rebekkah Dongall', '0141 Elka Hill', 35);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Maurie Witherden', '4 American Center', 169);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Damiano Blaske', '3 Pine View Plaza', 25);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Barbie Danne', '86 Oxford Alley', 40);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Jacenta Hatcher', '9344 Sommers Junction', 18);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Victoir Lintill', '2825 Bluejay Alley', 135);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Ring De Few', '4778 Oak Alley', 108);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Paulo Mateo', '7927 Weeping Birch Avenue', 16);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Elayne Morrowe', '201 Leroy Way', 114);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Aurelie Handsheart', '951 Dwight Lane', 144);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Robby Litzmann', '9 6th Park', 36);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Harrietta Luca', '9776 Warner Hill', 136);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Bathsheba Matheson', '37 Leroy Pass', 45);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Bobinette Moro', '1 Pierstorff Avenue', 103);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Diena Deners', '7255 Elmside Hill', 101);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Hester Saggers', '550 Russell Crossing', 52);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Jack Klainman', '0926 Hazelcrest Center', 114);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Iain Allnatt', '10 Derek Way', 38);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Jose Phittiplace', '0 Becker Junction', 58);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Mariele Yele', '53 Lindbergh Trail', 146);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Grayce Berzen', '0405 Northview Circle', 32);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Tatum Fowden', '8 Hooker Crossing', 70);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Gretal Collier', '7 Anniversary Lane', 81);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Almeria Chave', '6660 Transport Lane', 94);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Brunhilda Spurdon', '021 Amoth Place', 101);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Kimmy Fuggle', '802 Mandrake Place', 135);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Caria Barge', '2 Annamark Crossing', 105);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Fairleigh Fison', '8290 Gerald Drive', 60);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Dud Rawlcliffe', '4 Dayton Avenue', 164);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Lucho Boorne', '6246 Nancy Place', 87);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Aeriel Janaway', '232 Jenifer Park', 112);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Beauregard LLelweln', '57 Coleman Circle', 151);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Leoline Tappin', '454 Mallory Pass', 134);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Else Mueller', '774 Packers Trail', 153);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Simmonds Bendley', '2138 Kedzie Place', 154);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Randy Yoseloff', '740 Sutherland Parkway', 112);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Shane Matthis', '5684 Shasta Way', 15);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Marylynne Ofield', '37158 Towne Road', 140);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Locke Jery', '5672 American Ash Pass', 123);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Grazia Dabes', '9937 Duke Terrace', 107);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Paul Brownstein', '668 Briar Crest Trail', 45);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Ginny Gaydon', '0995 Hanson Road', 23);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Donni Quigg', '06 Doe Crossing Junction', 17);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Daren Whiffen', '1160 Lillian Plaza', 56);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Lacy Spurret', '5 Hoffman Plaza', 19);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Rosabella Camilleri', '892 Kedzie Road', 31);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Genevra Anstiss', '6969 Mitchell Junction', 71);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Kearney Garm', '039 Monterey Junction', 147);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Gwen Goneau', '10 Northwestern Pass', 159);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Livvy Le Port', '32230 Bashford Center', 43);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Sara Baxstair', '93698 Del Mar Trail', 92);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Grove Wall', '48 Beilfuss Circle', 16);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Bradley Buffey', '87335 Bobwhite Street', 144);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Clea Kitching', '89 Warner Crossing', 144);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Claybourne Saile', '51506 6th Terrace', 66);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Moore Borghese', '81 3rd Crossing', 163);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Natty Behne', '02617 Ryan Park', 94);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Micheal Augie', '37865 Maywood Pass', 48);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Deina Titta', '25 Steensland Lane', 26);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Chandal McDool', '019 Twin Pines Point', 136);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Clerc Badam', '48 Bartillon Point', 66);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Easter Bredbury', '7757 Ridge Oak Parkway', 108);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Yankee Girvan', '8 Blaine Park', 116);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Sisile O''Nion', '468 Vera Place', 47);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Alasteir Frier', '022 Lakeland Circle', 19);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Hart Hess', '89506 Helena Hill', 10);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Tawsha Revington', '5273 Briar Crest Lane', 85);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Rowe Fawks', '43 Bunker Hill Way', 74);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Mathilda Spriggin', '23 Scoville Plaza', 52);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Rosanne Hinsche', '1478 Manufacturers Park', 91);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Turner Lown', '50366 Fulton Plaza', 56);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Rosalia McTaggart', '15 Fieldstone Parkway', 23);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Robby Corbett', '69 Dawn Junction', 34);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Hollyanne Drohane', '62 Hanson Junction', 63);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Carin Husband', '93219 Becker Junction', 15);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Chan Errigo', '6337 Mallory Alley', 23);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Antin Bucher', '28 Pearson Point', 114);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Roxy MacGoun', '94713 Burning Wood Drive', 106);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Honey Tibols', '7076 Scofield Point', 66);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Maia Jewer', '75 Spohn Circle', 100);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Bartholemy McCard', '6758 Miller Avenue', 38);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Lavinie Crighten', '53 Anderson Trail', 39);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Micheal Desforges', '06 Texas Lane', 146);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Dalila Lummis', '25 Heffernan Pass', 21);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Ailina Menci', '50 Mcbride Circle', 141);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Jinny Lamberti', '7516 Anthes Point', 68);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Sebastian Doddridge', '15 Hintze Parkway', 83);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Nisse Orsay', '654 Village Green Way', 101);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Pamella Garms', '805 Transport Way', 154);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Ysabel Pearman', '2646 Ilene Center', 38);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Merrick Benet', '3368 1st Terrace', 168);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Bayard Lucius', '02906 Pierstorff Parkway', 161);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Rosemary Gariff', '803 Bonner Place', 87);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Norah Richardin', '0923 Veith Lane', 27);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Judi Betteridge', '73 Annamark Place', 134);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Theodosia Ambrus', '415 Bluestem Trail', 3);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Delly Commins', '8680 Darwin Crossing', 112);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Edyth Cogdell', '79 Shasta Drive', 12);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Cordie Burnet', '8 Moulton Way', 159);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Blake Fesby', '341 Trailsway Hill', 160);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Adolphe Asbrey', '91377 Muir Crossing', 106);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Catherina Blaine', '29545 Ludington Court', 55);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Kessia Dan', '61361 Green Park', 84);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Lory De Bellis', '13715 Moulton Lane', 25);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Eimile Spall', '05 Portage Trail', 70);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Reilly Miller', '718 5th Pass', 143);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Emily Tungate', '2 Jackson Road', 92);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Ellis Rhydderch', '897 Little Fleur Point', 7);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Hyacinth Tonn', '68 Sherman Parkway', 139);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Karola Braffington', '13 Corry Avenue', 51);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Annalee Winnard', '22 Center Park', 137);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Kermit Jervis', '443 Warrior Point', 72);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Fabio Cornelisse', '80946 Farwell Drive', 168);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Violet Jovis', '06 Fair Oaks Place', 128);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Eleanore Adlard', '0 Glendale Road', 100);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Mira Hutcheon', '9957 Lawn Pass', 22);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Jocelyn Betho', '01779 Meadow Valley Lane', 102);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Nicolea Maymond', '28839 Fallview Pass', 85);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Elia Gabbot', '15646 Armistice Circle', 30);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Ameline Garwell', '8 Hazelcrest Court', 59);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Read Sowman', '31662 Birchwood Junction', 6);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Gretel Jaine', '05 Acker Alley', 165);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Galina Elsdon', '58166 Schiller Avenue', 165);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Keefer Acres', '39 Dovetail Road', 2);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Nollie Hardey', '82229 Sutherland Street', 24);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Teresina O''Flynn', '31583 Maple Wood Lane', 10);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Lelia Revill', '7751 Nelson Drive', 165);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Brigg Wallage', '9527 Fair Oaks Center', 13);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Kandace Arnaez', '148 Almo Park', 4);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Nefen MacCrackan', '84 East Center', 128);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Anne Sangra', '557 Bartillon Way', 87);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Sanford Fellis', '18574 Sycamore Junction', 86);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Solly Ickowicz', '3952 Beilfuss Park', 25);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Waly Sallarie', '5820 David Terrace', 161);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Salvador Kiln', '4311 Surrey Court', 161);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Ernest Spreadbury', '62 Sommers Lane', 55);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Roxanna Pescud', '9028 Ryan Parkway', 62);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Susann Honisch', '28242 Steensland Parkway', 42);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Ellerey Moyle', '65575 Atwood Terrace', 128);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Stacy Carruth', '3 Declaration Lane', 67);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Cassi Merit', '5 Arkansas Point', 152);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Fianna Snyder', '59 3rd Place', 121);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Hewitt Sherston', '19 Graedel Street', 78);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Drew Lorente', '42 Fisk Road', 26);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Ginni Richings', '4960 Homewood Drive', 161);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Rutter O''Fihily', '70 Fisk Hill', 87);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Hillel Van Oort', '96 Veith Road', 167);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Gae Ditchfield', '6 Center Trail', 8);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Birgit Habbijam', '7 Lunder Parkway', 123);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Erma Legier', '70 Parkside Place', 129);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Purcell Everleigh', '73 Fairfield Trail', 5);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Malva Twitty', '4 Manley Circle', 28);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Johann Billington', '7388 Logan Point', 134);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Manolo Pawelek', '54 Spenser Court', 45);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Kristyn Glencorse', '052 Anzinger Point', 3);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Jacquie Paolone', '70015 Nova Hill', 90);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Hazlett Hurll', '145 Bonner Avenue', 131);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Rriocard Baccas', '52553 Armistice Circle', 70);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Nancy Dotterill', '2140 Prentice Junction', 80);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Sean Kerslake', '26749 Luster Parkway', 61);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Ortensia Durtnel', '45445 Saint Paul Terrace', 15);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Langsdon Tonnesen', '864 Continental Plaza', 103);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Siouxie Bonnett', '3 Buena Vista Pass', 147);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Emmet Corby', '04 Northland Trail', 32);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Cortie Dacke', '5 Bashford Center', 22);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Jeana Grinnikov', '21 Hollow Ridge Road', 6);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Clementine Auty', '877 Vera Plaza', 91);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Byron Welberry', '2 Glendale Plaza', 10);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Gael Romei', '625 Mariners Cove Alley', 66);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Rosaleen Kennedy', '24209 Carioca Plaza', 81);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Kare Behan', '013 Walton Circle', 47);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Erhard Sealand', '8 Florence Junction', 149);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Freddy Wickling', '8 Spaight Plaza', 40);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Rudolf Ioselevich', '44125 Fairview Trail', 19);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Ermina Etty', '730 Basil Drive', 5);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Filippa McCanny', '0459 Londonderry Trail', 74);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Daisi Arthurs', '469 Stang Pass', 24);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Niccolo Lourens', '653 Nancy Way', 161);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Neale Whitebread', '0 Oak Valley Point', 87);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Cymbre Cocci', '685 Pennsylvania Pass', 122);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Carol Bleas', '8428 Old Gate Park', 129);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Issiah Geraghty', '6 Ridgeview Road', 110);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Aldridge Van der Son', '10663 Straubel Alley', 106);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Verge Girod', '427 Arizona Plaza', 152);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Bethena Leyton', '62963 Huxley Parkway', 64);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Dorthea Gherarducci', '09 Morrow Avenue', 39);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Bradan Gales', '1262 Evergreen Avenue', 79);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Brien Dabourne', '2 Dennis Trail', 96);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Fabien Yockley', '2 Macpherson Circle', 120);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Theo Cockell', '51206 Green Ridge Terrace', 7);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Kacey Woolard', '993 Ilene Park', 94);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Jim Roslen', '0 Buhler Center', 94);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Becca Quadrio', '6 Prairie Rose Plaza', 40);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Marchelle Corley', '2 Northland Way', 36);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Damaris Penrith', '7 Sunbrook Pass', 81);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Nap Huett', '336 Southridge Avenue', 100);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Leonid Siberry', '09465 Meadow Valley Way', 169);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Gabie Pickthorn', '57 Anzinger Pass', 86);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Damita Glantz', '8224 Bunker Hill Hill', 166);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Hillary Prestidge', '846 Coleman Lane', 62);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Cindee Vincent', '3 Oriole Plaza', 139);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Lexi Itzkovici', '80728 Evergreen Way', 102);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Hugibert Stopher', '45895 Maple Wood Parkway', 106);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Ferguson Rudyard', '86 Cordelia Court', 104);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Elvin Trice', '38 Mcguire Court', 17);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Ansley Lalevee', '9 Golf Place', 20);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Jerrilee Blesing', '55 Merrick Plaza', 84);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Venus Sarfass', '96 Texas Plaza', 112);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Aretha Judron', '312 Schmedeman Parkway', 159);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Claiborn Dimmock', '90 Hanson Way', 77);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Wilfred Muffen', '7 Melby Terrace', 108);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Lia Gibke', '7 East Court', 122);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Marcos Count', '36 Summit Alley', 7);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Aeriel Ferandez', '5 Hollow Ridge Crossing', 62);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Ardith Resun', '6 Bartelt Junction', 150);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Vail Bagshawe', '5454 Stang Trail', 95);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Conway O''Donovan', '67 Oriole Lane', 116);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Othello Matzke', '946 Wayridge Crossing', 95);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Moina Chenery', '96 Spaight Street', 5);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Tedda Baumaier', '3159 Sycamore Junction', 73);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Benedetto McGraffin', '43 Bowman Park', 27);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Michal Dart', '6243 Mayfield Center', 54);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Hartley Kivlin', '80296 Wayridge Street', 153);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Meridith Starkings', '0559 Florence Plaza', 115);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Noland Heinish', '532 Vidon Pass', 136);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Nanice Casse', '9 Longview Park', 143);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Fred Gilbart', '5 Elka Road', 165);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Loni Sobczak', '152 Melvin Road', 156);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Constantina Harpham', '6 Nancy Point', 140);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Gabriela Gossage', '41286 Scoville Way', 88);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Joela Hupka', '0134 Ryan Trail', 113);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Mikey Frankiss', '4847 Farwell Avenue', 132);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Hobie Attenborough', '22 Spaight Trail', 12);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Jerald Riggs', '88 Hermina Park', 97);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Armand Joannet', '64 Carberry Circle', 132);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Kay Cunnington', '788 Oneill Plaza', 59);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Erminia McIlwraith', '9 Lawn Way', 168);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Obadiah Bryning', '4545 Moulton Road', 150);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Desiri Dunlea', '8500 Anthes Center', 153);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Holly Forrestall', '2 Dunning Circle', 81);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Star Sandiland', '20456 Ludington Lane', 79);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Cele Monteaux', '60631 Prentice Crossing', 170);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Ebeneser Yanov', '01 Ludington Court', 63);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Reider Kubu', '8250 7th Terrace', 51);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Marilee Parlatt', '93 Golden Leaf Park', 125);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Lucy Wolstencroft', '6 Glendale Alley', 61);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Lucina Escalante', '03600 Stang Pass', 152);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Marthena Fairbank', '14 Ridge Oak Alley', 97);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Joanna Mounsie', '79 Donald Trail', 38);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Reena Budibent', '16208 Stephen Plaza', 162);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Cecilla Rodolphe', '2 Orin Lane', 7);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Harmonie Deaves', '7 Nelson Place', 100);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Adena Danbury', '67310 Elgar Avenue', 118);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Alla Levane', '0 Roth Pass', 82);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Meara Feldmark', '44057 Scoville Pass', 150);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Dare Cargenven', '538 Westerfield Street', 87);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Yuma Surgood', '24084 Schmedeman Crossing', 52);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Jobey Caldicot', '2 Wayridge Court', 6);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Sarita Tawton', '75 Transport Circle', 168);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Dolf Weld', '0 Swallow Hill', 100);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Tricia MacDermot', '480 Sauthoff Alley', 89);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Christen Howsam', '92 Hanson Point', 55);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Estella Varker', '9 Daystar Street', 83);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Zane Hovenden', '6 Mayer Center', 21);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Sofie Speechly', '9011 Truax Road', 129);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Allissa Yakhin', '2 Huxley Way', 145);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Carlo Louedey', '9931 Lillian Park', 10);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Lizzie Spurrior', '82 Memorial Point', 51);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Dominik Chessun', '525 Longview Parkway', 19);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Berni Traill', '2247 Loftsgordon Point', 72);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Nikolaus MacAndreis', '843 Oak Park', 130);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Bill Cringle', '73178 Brickson Park Parkway', 134);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Haley Draycott', '619 Hollow Ridge Court', 93);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Nick Uzielli', '86 Meadow Vale Crossing', 36);
insert into "Student" ("StudentID", "StudentName", "Address", "Course") values (DEFAULT, 'Essa Lennie', '026 Lien Crossing', 141);
